// Closed-class words are enumerated. Open-class words are recognised by the
// semantic tables below, and anything unknown falls through to morphology in
// parse.js. Nothing here calls a model.

export const DETERMINERS = new Set([
  'a', 'an', 'the', 'this', 'that', 'these', 'those', 'my', 'your', 'his',
  'her', 'its', 'our', 'their', 'every', 'each', 'some', 'any', 'no', 'another',
  'both', 'either', 'neither', 'much', 'many', 'few', 'several', 'all',
]);

export const PRONOUNS = new Set([
  'i', 'you', 'he', 'she', 'it', 'we', 'they', 'me', 'him', 'us', 'them',
  'who', 'what', 'which', 'someone', 'something', 'nobody', 'nothing',
  'everyone', 'everything', 'anyone', 'anything', 'himself', 'herself',
  'itself', 'themselves', 'myself', 'yourself',
]);

export const AUXILIARIES = new Set([
  'is', 'am', 'are', 'was', 'were', 'be', 'been', 'being', 'do', 'does',
  'did', 'have', 'has', 'had', 'will', 'would', 'shall', 'should', 'can',
  'could', 'may', 'might', 'must', 'ought',
]);

export const CONJUNCTIONS = new Set([
  'and', 'or', 'but', 'nor', 'yet', 'so', 'while', 'whereas', 'then',
]);

export const NEGATORS = new Set(['not', "n't", 'never', 'no', 'without', 'nothing', 'nobody']);

export const NUMBERS = {
  one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8,
  nine: 9, ten: 10, eleven: 11, twelve: 12, dozen: 12, twenty: 16,
  hundred: 20, thousand: 24, single: 1, twin: 2, triple: 3, countless: 14,
};

// Prepositions are the load-bearing part of the grammar: each one names a real
// spatial relation the builder is required to honour geometrically.
// `relation` is consumed by architecture.js. None of this is decorative.
export const PREPOSITIONS = {
  on: 'stack', upon: 'stack', atop: 'stack', onto: 'stack', over: 'span',
  above: 'float', under: 'sink', underneath: 'sink', beneath: 'sink',
  below: 'sink',
  in: 'nest', inside: 'nest', within: 'nest', into: 'nest', amid: 'nest',
  among: 'nest', of: 'nest',
  through: 'pierce', across: 'span', along: 'flank', past: 'flank',
  beside: 'adjacent', by: 'adjacent', with: 'adjacent', near: 'adjacent',
  against: 'adjacent', for: 'adjacent', like: 'adjacent',
  beyond: 'far', behind: 'behind', before: 'front',
  toward: 'approach', towards: 'approach', to: 'approach', at: 'approach',
  from: 'depart', off: 'depart', out: 'depart',
  around: 'encircle', about: 'encircle',
  without: 'absent', between: 'straddle', during: 'flank',
};

// Verb class decides the topology of the central hall. A sentence about motion
// must not produce the same room as a sentence about collapse.
const VERB_CLASSES = {
  motion: [
    'walk', 'walks', 'walked', 'walking', 'run', 'runs', 'ran', 'running',
    'fly', 'flies', 'flew', 'flying', 'move', 'moves', 'moved', 'moving',
    'travel', 'travels', 'drift', 'drifts', 'drifted', 'drifting', 'fall',
    'falls', 'fell', 'falling', 'climb', 'climbs', 'climbed', 'climbing',
    'swim', 'swims', 'crawl', 'crawls', 'slide', 'slides', 'wander',
    'wanders', 'march', 'marches', 'flow', 'flows', 'flowed', 'flowing',
    'descend', 'descends', 'ascend', 'ascends', 'enter', 'enters', 'entered',
    'leave', 'leaves', 'escape', 'escapes', 'arrive', 'arrives',
    'cross', 'crosses', 'crossed', 'return', 'returns', 'returned',
    'sink', 'sinks', 'sank', 'sinking',
  ],
  transfer: [
    'give', 'gives', 'gave', 'giving', 'send', 'sends', 'sent', 'sending',
    'carry', 'carries', 'carried', 'carrying', 'bring', 'brings', 'brought',
    'take', 'takes', 'took', 'taking', 'throw', 'throws', 'threw', 'throwing',
    'pass', 'passes', 'passed', 'hand', 'hands', 'handed', 'trade', 'trades',
    'sell', 'sells', 'sold', 'buy', 'buys', 'bought', 'pay', 'pays', 'paid',
    'lend', 'lends', 'offer', 'offers', 'offered', 'deliver', 'delivers',
  ],
  perception: [
    'see', 'sees', 'saw', 'seeing', 'look', 'looks', 'looked', 'looking',
    'watch', 'watches', 'watched', 'watching', 'hear', 'hears', 'heard',
    'listen', 'listens', 'listened', 'feel', 'feels', 'felt', 'sense',
    'senses', 'observe', 'observes', 'observed', 'notice', 'notices',
    'find', 'finds', 'found', 'search', 'searches', 'seek', 'seeks',
    'remember', 'remembers', 'remembered', 'forget', 'forgets', 'forgot',
    'dream', 'dreams', 'dreamed', 'dreamt', 'know', 'knows', 'knew',
    'think', 'thinks', 'thought', 'wait', 'waits', 'waited', 'waiting',
  ],
  creation: [
    'build', 'builds', 'built', 'make', 'makes', 'made', 'making',
    'create', 'creates', 'created', 'creating', 'grow', 'grows', 'grew',
    'growing', 'write', 'writes', 'wrote', 'writing', 'draw', 'draws',
    'drew', 'paint', 'paints', 'painted', 'plant', 'plants', 'planted',
    'weave', 'weaves', 'wove', 'forge', 'forges', 'forged', 'raise',
    'raises', 'raised', 'assemble', 'assembles', 'generate', 'generates',
    'generated', 'compose', 'composes', 'invent', 'invents', 'design',
    'designs', 'designed', 'open', 'opens', 'opened', 'begin', 'begins',
  ],
  destruction: [
    'break', 'breaks', 'broke', 'broken', 'breaking', 'burn', 'burns',
    'burned', 'burnt', 'burning', 'destroy', 'destroys', 'destroyed',
    'collapse', 'collapses', 'collapsed', 'shatter', 'shatters',
    'shattered', 'crush', 'crushes', 'crushed', 'tear', 'tears', 'tore',
    'cut', 'cuts', 'kill', 'kills', 'killed', 'die', 'dies', 'died',
    'dying', 'fade', 'fades', 'faded', 'drown', 'drowns', 'drowned',
    'erase', 'erases', 'erased', 'end', 'ends',
    'ended', 'close', 'closes', 'closed', 'lose', 'loses', 'lost',
  ],
  utterance: [
    'say', 'says', 'said', 'speak', 'speaks', 'spoke', 'tell', 'tells',
    'told', 'ask', 'asks', 'asked', 'answer', 'answers', 'answered',
    'sing', 'sings', 'sang', 'call', 'calls', 'called', 'shout', 'shouts',
    'whisper', 'whispers', 'whispered', 'read', 'reads', 'name', 'names',
    'named', 'describe', 'describes', 'described', 'declare', 'declares',
  ],
};

export const VERBS = new Map();
for (const [cls, words] of Object.entries(VERB_CLASSES)) {
  for (const w of words) if (!VERBS.has(w)) VERBS.set(w, cls);
}

// The default class: copulas and anything verb-shaped but unlisted.
export const STATIVE = new Set([
  'is', 'am', 'are', 'was', 'were', 'be', 'been', 'being', 'stand', 'stands',
  'stood', 'sit', 'sits', 'sat', 'lie', 'lies', 'lay', 'rest', 'rests',
  'rested', 'remain', 'remains', 'remained', 'stay', 'stays', 'stayed',
  'hold', 'holds', 'held', 'keep', 'keeps', 'kept', 'live', 'lives', 'lived',
  'exist', 'exists', 'sleep', 'sleeps', 'slept', 'hang', 'hangs', 'hung',
  'belong', 'belongs', 'have', 'has', 'had', 'own', 'owns', 'owned',
  'contain', 'contains', 'contained', 'wear', 'wears', 'wore', 'want',
  'wants', 'wanted', 'love', 'loves', 'loved', 'need', 'needs', 'needed',
]);

// Nouns carry the two numbers the builder needs: how big the volume is and how
// solid it is. `element` selects a material family from ELEMENTS.
// scale runs 0.35 tiny to 3.0 vast; mass runs 0 void to 1 solid.
const NOUN_TABLE = {
  mountain: { scale: 3.0, mass: 1, element: 'stone' },
  city: { scale: 2.8, mass: 0.9, element: 'concrete' },
  ocean: { scale: 3.0, mass: 0.15, element: 'water' },
  sea: { scale: 2.7, mass: 0.15, element: 'water' },
  sky: { scale: 3.0, mass: 0.05, element: 'air' },
  desert: { scale: 2.9, mass: 0.6, element: 'sand' },
  forest: { scale: 2.6, mass: 0.7, element: 'wood' },
  river: { scale: 2.2, mass: 0.2, element: 'water', aspect: [1.5, 0.14, 3.6] },
  lake: { scale: 2.2, mass: 0.2, element: 'water' },
  valley: { scale: 2.6, mass: 0.3, element: 'stone' },
  island: { scale: 2.2, mass: 0.8, element: 'stone' },
  world: { scale: 3.0, mass: 0.6, element: 'concrete' },
  cathedral: { scale: 2.6, mass: 0.95, element: 'stone', aspect: [1.0, 1.5, 1.9] },
  tower: { scale: 2.4, mass: 0.9, element: 'concrete', aspect: [0.5, 2.6, 0.5] },
  bridge: { scale: 2.2, mass: 0.85, element: 'metal', aspect: [0.5, 0.3, 3.4] },
  library: { scale: 2.0, mass: 0.85, element: 'wood' },
  temple: { scale: 2.2, mass: 0.95, element: 'stone' },
  palace: { scale: 2.4, mass: 0.9, element: 'stone' },
  factory: { scale: 2.2, mass: 0.85, element: 'metal' },
  station: { scale: 2.0, mass: 0.8, element: 'metal' },
  market: { scale: 2.0, mass: 0.6, element: 'cloth' },
  garden: { scale: 1.9, mass: 0.4, element: 'wood' },
  house: { scale: 1.4, mass: 0.9, element: 'wood' },
  home: { scale: 1.4, mass: 0.9, element: 'wood' },
  building: { scale: 1.9, mass: 0.9, element: 'concrete' },
  room: { scale: 1.2, mass: 0.8, element: 'plaster' },
  hall: { scale: 1.8, mass: 0.8, element: 'plaster' },
  corridor: { scale: 1.4, mass: 0.7, element: 'plaster', aspect: [0.5, 1.2, 3.2] },
  stair: { scale: 1.2, mass: 0.8, element: 'concrete' },
  staircase: { scale: 1.4, mass: 0.8, element: 'concrete', aspect: [0.8, 1.4, 2.0] },
  door: { scale: 0.9, mass: 0.5, element: 'wood', aspect: [0.8, 2.0, 0.2] },
  gate: { scale: 1.4, mass: 0.7, element: 'metal' },
  window: { scale: 0.9, mass: 0.15, element: 'glass', aspect: [1.1, 1.4, 0.18] },
  wall: { scale: 1.6, mass: 1, element: 'concrete', aspect: [2.6, 1.5, 0.22] },
  roof: { scale: 1.7, mass: 0.8, element: 'metal' },
  floor: { scale: 1.7, mass: 0.9, element: 'stone' },
  column: { scale: 1.1, mass: 1, element: 'stone', aspect: [0.38, 3.0, 0.38] },
  arch: { scale: 1.3, mass: 0.85, element: 'stone' },
  ruin: { scale: 1.8, mass: 0.55, element: 'stone' },
  machine: { scale: 1.3, mass: 0.9, element: 'metal' },
  engine: { scale: 1.2, mass: 0.95, element: 'metal' },
  clock: { scale: 0.9, mass: 0.8, element: 'metal' },
  mirror: { scale: 0.9, mass: 0.3, element: 'glass' },
  glass: { scale: 0.8, mass: 0.2, element: 'glass' },
  lamp: { scale: 0.6, mass: 0.4, element: 'light' },
  light: { scale: 0.8, mass: 0.05, element: 'light' },
  lantern: { scale: 0.55, mass: 0.35, element: 'light' },
  fire: { scale: 1.1, mass: 0.1, element: 'fire' },
  flame: { scale: 0.8, mass: 0.1, element: 'fire' },
  sun: { scale: 2.4, mass: 0.05, element: 'light' },
  moon: { scale: 1.8, mass: 0.4, element: 'stone' },
  star: { scale: 1.0, mass: 0.05, element: 'light' },
  shadow: { scale: 1.4, mass: 0.02, element: 'void' },
  darkness: { scale: 1.8, mass: 0.02, element: 'void' },
  silence: { scale: 1.6, mass: 0.03, element: 'void' },
  memory: { scale: 1.4, mass: 0.1, element: 'void' },
  dream: { scale: 1.6, mass: 0.08, element: 'void' },
  ghost: { scale: 1.1, mass: 0.05, element: 'void' },
  time: { scale: 2.0, mass: 0.05, element: 'void' },
  water: { scale: 1.6, mass: 0.15, element: 'water' },
  rain: { scale: 1.8, mass: 0.1, element: 'water' },
  snow: { scale: 1.8, mass: 0.2, element: 'water' },
  ice: { scale: 1.5, mass: 0.7, element: 'glass' },
  wind: { scale: 2.0, mass: 0.03, element: 'air' },
  storm: { scale: 2.4, mass: 0.15, element: 'air' },
  cloud: { scale: 2.0, mass: 0.08, element: 'air' },
  smoke: { scale: 1.6, mass: 0.06, element: 'air' },
  stone: { scale: 1.1, mass: 1, element: 'stone' },
  rock: { scale: 1.2, mass: 1, element: 'stone' },
  sand: { scale: 1.4, mass: 0.5, element: 'sand' },
  metal: { scale: 1.1, mass: 1, element: 'metal' },
  iron: { scale: 1.1, mass: 1, element: 'metal' },
  gold: { scale: 0.9, mass: 1, element: 'gold' },
  silver: { scale: 0.9, mass: 1, element: 'metal' },
  wood: { scale: 1.1, mass: 0.85, element: 'wood' },
  tree: { scale: 1.7, mass: 0.75, element: 'wood', aspect: [0.45, 2.3, 0.45] },
  flower: { scale: 0.5, mass: 0.3, element: 'cloth' },
  leaf: { scale: 0.45, mass: 0.2, element: 'cloth' },
  root: { scale: 1.2, mass: 0.7, element: 'wood' },
  seed: { scale: 0.4, mass: 0.6, element: 'wood' },
  bird: { scale: 0.6, mass: 0.35, element: 'cloth' },
  fish: { scale: 0.6, mass: 0.45, element: 'water' },
  horse: { scale: 1.2, mass: 0.8, element: 'cloth' },
  dog: { scale: 0.8, mass: 0.7, element: 'cloth' },
  cat: { scale: 0.6, mass: 0.6, element: 'cloth' },
  child: { scale: 0.8, mass: 0.7, element: 'cloth' },
  man: { scale: 1.0, mass: 0.75, element: 'cloth' },
  woman: { scale: 1.0, mass: 0.75, element: 'cloth' },
  person: { scale: 1.0, mass: 0.75, element: 'cloth' },
  people: { scale: 1.8, mass: 0.7, element: 'cloth' },
  crowd: { scale: 2.0, mass: 0.65, element: 'cloth' },
  king: { scale: 1.2, mass: 0.8, element: 'gold' },
  god: { scale: 2.2, mass: 0.3, element: 'light' },
  book: { scale: 0.6, mass: 0.7, element: 'wood' },
  page: { scale: 0.45, mass: 0.3, element: 'cloth' },
  word: { scale: 0.5, mass: 0.4, element: 'void' },
  sentence: { scale: 1.0, mass: 0.5, element: 'void' },
  language: { scale: 1.8, mass: 0.3, element: 'void' },
  song: { scale: 1.2, mass: 0.15, element: 'void' },
  voice: { scale: 1.0, mass: 0.12, element: 'void' },
  name: { scale: 0.8, mass: 0.3, element: 'void' },
  story: { scale: 1.6, mass: 0.3, element: 'void' },
  road: { scale: 2.0, mass: 0.6, element: 'concrete', aspect: [0.55, 0.08, 4.2] },
  path: { scale: 1.6, mass: 0.5, element: 'sand', aspect: [0.4, 0.06, 4.0] },
  street: { scale: 2.0, mass: 0.6, element: 'concrete', aspect: [0.6, 0.08, 4.2] },
  train: { scale: 1.8, mass: 0.9, element: 'metal', aspect: [0.5, 0.7, 4.0] },
  ship: { scale: 2.0, mass: 0.85, element: 'metal', aspect: [0.6, 0.9, 2.8] },
  boat: { scale: 1.3, mass: 0.7, element: 'wood' },
  car: { scale: 1.2, mass: 0.85, element: 'metal' },
  wheel: { scale: 0.9, mass: 0.8, element: 'metal' },
  key: { scale: 0.4, mass: 0.8, element: 'metal' },
  coin: { scale: 0.35, mass: 0.9, element: 'gold' },
  knife: { scale: 0.5, mass: 0.9, element: 'metal' },
  hand: { scale: 0.6, mass: 0.7, element: 'cloth' },
  eye: { scale: 0.5, mass: 0.4, element: 'glass' },
  heart: { scale: 0.7, mass: 0.7, element: 'fire' },
  head: { scale: 0.7, mass: 0.75, element: 'cloth' },
  body: { scale: 1.1, mass: 0.8, element: 'cloth' },
  bone: { scale: 0.7, mass: 0.9, element: 'stone' },
  blood: { scale: 0.9, mass: 0.2, element: 'fire' },
  skin: { scale: 0.9, mass: 0.4, element: 'cloth' },
  night: { scale: 2.4, mass: 0.05, element: 'void' },
  day: { scale: 2.4, mass: 0.08, element: 'light' },
  morning: { scale: 2.0, mass: 0.08, element: 'light' },
  winter: { scale: 2.4, mass: 0.2, element: 'water' },
  summer: { scale: 2.4, mass: 0.15, element: 'light' },
  war: { scale: 2.6, mass: 0.4, element: 'fire' },
  peace: { scale: 2.2, mass: 0.2, element: 'light' },
  love: { scale: 1.6, mass: 0.2, element: 'fire' },
  fear: { scale: 1.6, mass: 0.15, element: 'void' },
  hope: { scale: 1.6, mass: 0.15, element: 'light' },
  agent: { scale: 1.1, mass: 0.6, element: 'metal' },
  robot: { scale: 1.2, mass: 0.9, element: 'metal' },
  computer: { scale: 1.0, mass: 0.85, element: 'metal' },
  network: { scale: 2.0, mass: 0.3, element: 'light' },
  data: { scale: 1.6, mass: 0.25, element: 'light' },
  model: { scale: 1.4, mass: 0.5, element: 'metal' },
  system: { scale: 1.8, mass: 0.6, element: 'metal' },
};

export const NOUNS = new Map(Object.entries(NOUN_TABLE));

// Adjectives write straight into the material and the volume. Any field left
// undefined is not applied, so adjectives compose on one noun.
const ADJ_TABLE = {
  vast: { scale: 1.9 }, huge: { scale: 1.7 }, enormous: { scale: 1.8 },
  giant: { scale: 1.7 }, great: { scale: 1.4 }, large: { scale: 1.4 },
  big: { scale: 1.4 }, tall: { scale: 1.3, stretchY: 1.9 },
  high: { scale: 1.2, stretchY: 1.7 }, deep: { stretchY: 1.5, sink: true },
  long: { stretchZ: 2.1 }, wide: { stretchX: 1.9 },
  narrow: { stretchX: 0.45 }, thin: { stretchX: 0.5, stretchZ: 0.5 },
  small: { scale: 0.62 }, little: { scale: 0.6 }, tiny: { scale: 0.42 },
  short: { scale: 0.8, stretchY: 0.55 }, low: { stretchY: 0.5 },
  bright: { emissive: 2.2 }, glowing: { emissive: 2.6 },
  luminous: { emissive: 2.4 }, burning: { emissive: 3.0, color: 0xd8541f },
  shining: { emissive: 2.0 }, radiant: { emissive: 2.6 },
  dark: { emissive: 0, color: 0x1b1b1e, roughness: 0.95 },
  black: { color: 0x121214, roughness: 0.9 },
  white: { color: 0xf2efe9, roughness: 0.75 },
  grey: { color: 0x8b8b88 }, gray: { color: 0x8b8b88 },
  red: { color: 0xa8331f }, crimson: { color: 0x8e1f1f },
  blue: { color: 0x2f4f74 }, green: { color: 0x3d6b46 },
  gold: { color: 0xb08334, metalness: 1, roughness: 0.28 },
  golden: { color: 0xb08334, metalness: 1, roughness: 0.28 },
  silver: { color: 0xb9bcc0, metalness: 1, roughness: 0.22 },
  yellow: { color: 0xc9a227 }, orange: { color: 0xb96a2a },
  purple: { color: 0x53406b }, violet: { color: 0x5b4577 },
  pink: { color: 0xc08a92 }, brown: { color: 0x6b4f38 },
  rusted: { color: 0x8a4a2b, roughness: 0.95, metalness: 0.6 },
  rusty: { color: 0x8a4a2b, roughness: 0.95, metalness: 0.6 },
  glass: { transmission: 1, roughness: 0.05 },
  transparent: { transmission: 1, roughness: 0.02 },
  clear: { transmission: 0.9, roughness: 0.05 },
  invisible: { transmission: 1, opacity: 0.08, roughness: 0 },
  frozen: { color: 0xa9c4cc, transmission: 0.7, roughness: 0.15 },
  wet: { roughness: 0.08 }, smooth: { roughness: 0.1 },
  polished: { roughness: 0.06, metalness: 0.5 },
  rough: { roughness: 1 }, coarse: { roughness: 1 },
  metallic: { metalness: 1, roughness: 0.3 },
  wooden: { roughness: 0.75, color: 0x6f5237 },
  old: { roughness: 0.95, wear: 0.7 },
  ancient: { roughness: 1, wear: 0.9, scale: 1.2 },
  ruined: { wear: 1, fracture: true }, broken: { wear: 1, fracture: true },
  cracked: { wear: 0.8, fracture: true }, shattered: { wear: 1, fracture: true },
  new: { roughness: 0.35, wear: 0 }, clean: { roughness: 0.25, wear: 0 },
  empty: { hollow: true }, hollow: { hollow: true }, open: { hollow: true },
  quiet: { calm: 0.8 }, silent: { calm: 1 }, still: { calm: 1 },
  slow: { calm: 0.7 }, fast: { calm: 0 }, quick: { calm: 0 },
  endless: { repeat: 6, scale: 1.3 }, infinite: { repeat: 8, scale: 1.4 },
  countless: { repeat: 8 }, single: { repeat: 1 }, lonely: { repeat: 1 },
  cold: { color: 0x6f8894 }, warm: { color: 0xb98a52 },
  hot: { color: 0xb4552a, emissive: 0.8 },
  heavy: { mass: 1, scale: 1.2 }, soft: { roughness: 0.9, mass: 0.4 },
  hard: { roughness: 0.4, mass: 1 },
  sharp: { taper: 0.15 }, round: { round: true }, curved: { round: true },
  circular: { round: true },
  floating: { float: 3.5 }, hanging: { float: 2.5 }, rising: { float: 2 },
  falling: { sink: true }, buried: { sink: true }, sunken: { sink: true },
  hidden: { opacity: 0.35 }, secret: { opacity: 0.45 },
  distant: { far: 2.2 }, far: { far: 2.4 }, near: { far: 0.5 },
  close: { far: 0.5 }, first: { repeat: 1 }, last: { repeat: 1 },
  beautiful: { roughness: 0.25, emissive: 0.3 },
  strange: { skew: 0.35 }, wrong: { skew: 0.5 }, twisted: { skew: 0.6 },
  crooked: { skew: 0.45 }, tilted: { skew: 0.3 },
};

export const ADJECTIVES = new Map(Object.entries(ADJ_TABLE));

// Adverbs are scene-scope, not room-scope: they change the air of the whole
// build rather than any one volume.
export const ADVERBS = {
  slowly: { agentSpeed: 0.45, fog: 1.4 },
  quickly: { agentSpeed: 2.0, fog: 0.7 },
  quietly: { fog: 1.5, exposure: 0.8 },
  silently: { fog: 1.7, exposure: 0.72 },
  softly: { fog: 1.3, exposure: 0.9 },
  loudly: { exposure: 1.25, agentSpeed: 1.4 },
  suddenly: { agentSpeed: 2.4, exposure: 1.2 },
  always: { repeatWorld: 2 },
  almost: { opacity: 0.6 },
  barely: { opacity: 0.45, exposure: 0.8 },
  brightly: { exposure: 1.5 },
  darkly: { exposure: 0.6, fog: 1.6 },
  deeply: { fog: 1.5 },
  endlessly: { repeatWorld: 3 },
  forever: { repeatWorld: 3 },
  again: { repeatWorld: 2 },
  together: { cluster: 0.6 },
  apart: { cluster: 1.8 },
  away: { cluster: 2.0 },
};

export const ELEMENTS = {
  stone: { color: 0x8d8578, roughness: 0.88, metalness: 0 },
  concrete: { color: 0x9d9a93, roughness: 0.82, metalness: 0 },
  plaster: { color: 0xdcd6ca, roughness: 0.78, metalness: 0 },
  metal: { color: 0x6a6f75, roughness: 0.34, metalness: 1 },
  gold: { color: 0xb08334, roughness: 0.26, metalness: 1 },
  glass: { color: 0xbcd0d6, roughness: 0.06, metalness: 0, transmission: 0.92 },
  water: { color: 0x3d6478, roughness: 0.08, metalness: 0, transmission: 0.75 },
  wood: { color: 0x6f5237, roughness: 0.76, metalness: 0 },
  cloth: { color: 0xb8a894, roughness: 0.95, metalness: 0 },
  sand: { color: 0xc2ab86, roughness: 0.98, metalness: 0 },
  fire: { color: 0xc4551f, roughness: 0.5, metalness: 0, emissive: 1.6 },
  light: { color: 0xf0e6cf, roughness: 0.3, metalness: 0, emissive: 2.0 },
  air: { color: 0xc9d3d8, roughness: 0.4, metalness: 0, transmission: 0.6 },
  void: { color: 0x24242a, roughness: 0.95, metalness: 0, emissive: 0 },
};

export const DEFAULT_NOUN = { scale: 1.2, mass: 0.7, element: 'plaster' };
